query allJobsDelay($realm: Realm!, $startDate: Date!, $endDate: Date!) {
  allJobsDelay(
    realm: $realm,
    startDate: $startDate,
    endDate: $endDate
  ) {
    snapshotDate,
    delayDays,
    name
  }
}
